COUNTRIES = [
    {"slug":"albania","name":"Albania","osm":"Albania"},
    {"slug":"austria","name":"Austria","osm":"Austria"},
    {"slug":"belarus","name":"Belarus","osm":"Belarus"},
    {"slug":"belgium","name":"Belgium","osm":"Belgium"},
    {"slug":"bosnia","name":"Bosnia and Herzegovina","osm":"Bosnia and Herzegovina"},
    {"slug":"bulgaria","name":"Bulgaria","osm":"Bulgaria"},
    {"slug":"croatia","name":"Croatia","osm":"Croatia"},
    {"slug":"cyprus","name":"Cyprus","osm":"Cyprus"},
    {"slug":"czech-republic","name":"Czech Republic","osm":"Czechia"},
    {"slug":"denmark","name":"Denmark","osm":"Denmark"},
    {"slug":"estonia","name":"Estonia","osm":"Estonia"},
    {"slug":"finland","name":"Finland","osm":"Finland"},
    {"slug":"france","name":"France","osm":"France"},
    {"slug":"germany","name":"Germany","osm":"Germany"},
    {"slug":"greece","name":"Greece","osm":"Greece"},
    {"slug":"hungary","name":"Hungary","osm":"Hungary"},
    {"slug":"iceland","name":"Iceland","osm":"Iceland"},
    {"slug":"ireland","name":"Ireland","osm":"Ireland"},
    {"slug":"italy","name":"Italy","osm":"Italy"},
    {"slug":"kosovo","name":"Kosovo","osm":"Kosovo"},
    {"slug":"latvia","name":"Latvia","osm":"Latvia"},
    {"slug":"liechtenstein","name":"Liechtenstein","osm":"Liechtenstein"},
    {"slug":"lithuania","name":"Lithuania","osm":"Lithuania"},
    {"slug":"luxembourg","name":"Luxembourg","osm":"Luxembourg"},
    {"slug":"malta","name":"Malta","osm":"Malta"},
    {"slug":"moldova","name":"Moldova","osm":"Moldova"},
    {"slug":"montenegro","name":"Montenegro","osm":"Montenegro"},
    {"slug":"netherlands","name":"Netherlands","osm":"Netherlands"},
    {"slug":"north-macedonia","name":"North Macedonia","osm":"North Macedonia"},
    {"slug":"norway","name":"Norway","osm":"Norway"},
    {"slug":"poland","name":"Poland","osm":"Poland"},
    {"slug":"portugal","name":"Portugal","osm":"Portugal"},
    {"slug":"romania","name":"Romania","osm":"Romania"},
    {"slug":"serbia","name":"Serbia","osm":"Serbia"},
    {"slug":"slovakia","name":"Slovakia","osm":"Slovakia"},
    {"slug":"slovenia","name":"Slovenia","osm":"Slovenia"},
    {"slug":"spain","name":"Spain","osm":"Spain"},
    {"slug":"sweden","name":"Sweden","osm":"Sweden"},
    {"slug":"switzerland","name":"Switzerland","osm":"Switzerland"},
    {"slug":"ukraine","name":"Ukraine","osm":"Ukraine"},
    {"slug":"united-kingdom","name":"United Kingdom","osm":"United Kingdom"},
]
